name: staticgrad_python  # Replace 'myenv' with your desired environment name
channels:
  - defaults
  - conda-forge 
dependencies:
  - python 
  - numpy
  - transformers
  - pytorch
  - tqdm
  - pip
  - pip:
    - tiktoken